name: call-cicd-class-library

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  call-class-library:
    uses: gabriela-m-silva/esteiras-devops/.github/workflows/esteira-teste-conexao.yaml@main
    with:
      test-directory: 'src/UnitTestProject1'
      proj-directory: 'src/ClassLibrary1'
      project-type: 'ClassLibrary'
    secrets: inherit