name: call-cicd-class-library

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-class-library:
    uses: ./.github/workflows/cicd-class-library-reusable.yaml
    with:
      test-directory: 'src/UnitTestProject1'
      lib-directory: 'src/ClassLibrary1'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}